name: zran
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  # For packaging, and testing
  - setuptools
  - wheel
  - cython
  - pytest
  - pytest-console-scripts
  - pytest-cov
